services:
  postgres:
    image: postgres:16
    container_name: secureops-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend-Go/main
    container_name: secureops-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      RISK_SERVICE_URL: http://risk-service:8081
    depends_on:
      - postgres
      - risk-service
    ports:
      - "8080:8080"

  risk-service:
    build:
      context: ./backend-Go/risk-service
    container_name: secureops-risk-service
    restart: unless-stopped

volumes:
  postgres_data:
