
#sets the application name inside spring boot
spring.application.name=backend-springboot

#tells spring how to reach the database
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
#tells spring which JDBC driver to use for postgres
spring.datasource.driver-class-name=org.postgresql.Driver

#tells hibernate how to handle schema changes
spring.jpa.hibernate.ddl-auto=update
#prints SQL queries in the console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

